version: "3.9"
services:
  frontend:
    build:
      context: .
    volumes:
      - './src:/app/src'
    command: [ "npm", "run", "dev" ]
    ports:
      - '3000:3000'
  # backend:
  #   build:
  #     context: ./api/
  #   volumes:
  #     - './api:/app'
  #   command: [ "./init.sh" ]
  #   ports:
  #     - "1323:1323"
