version: "3.9"
services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    command: [ "npm", "run", "dev" ]
    ports:
      - '3000:3000'
volumes:
  nodemodules: {}
